os: osx
language: c
script: make
before_deploy:
- mkdir -p output
- cp ccid-installer.dmg ccid-*.tar.gz output
deploy:
    provider: releases
    file_glob: true
    file: deploy/*
    skip_cleanup: true
    on:
      tags: true
      repo: zwilla/osx-ccid-installer
      all_branches: true
